#!/usr/bin/env python3
"""Convert GitHub linguist's languages.yml into data/imported/linguist.toml.

Only detection facts cross: extensions, filenames, interpreters and the coarse
type. Everything linguist carries for syntax highlighting -- colours, tm_scope,
ace_mode, codemirror -- is upstream's business and is dropped.

Run with the upstream revision pinned, so the header records exactly what was
imported and the file can be regenerated and diffed:

    tools/import-linguist.py <revision>
"""
import hashlib
import json
import subprocess
import sys
import urllib.request

import yaml

UPSTREAM = "https://raw.githubusercontent.com/github-linguist/linguist/{rev}/lib/linguist/languages.yml"

# linguist's `type` is coarser than LanguageRole and does not name build files.
ROLE = {
    "programming": "programming",
    "markup": "markup",
    "data": "data",
    "prose": "documentation",
}


def slug(name):
    """`C#` -> `c-sharp`, matching the ids the curated profiles already use."""
    out = name.lower().replace("#", "-sharp").replace("++", "pp").replace("*", "-star")
    out = "".join(c if c.isalnum() else "-" for c in out)
    while "--" in out:
        out = out.replace("--", "-")
    return out.strip("-")


def main():
    revision = sys.argv[1] if len(sys.argv) > 1 else "main"
    url = UPSTREAM.format(rev=revision)
    raw = urllib.request.urlopen(url, timeout=60).read()
    digest = hashlib.sha256(raw).hexdigest()
    languages = yaml.safe_load(raw)

    lines = [
        "# @generated by tools/import-linguist.py. Do not edit by hand.",
        "#",
        "# Detection facts imported in bulk from GitHub linguist (MIT). These carry",
        "# no conventions, facets or toolchain data: a language here is a name and a",
        "# way to recognise it, nothing more. A curated file in data/languages/ with",
        "# the same id wins outright.",
        "#",
        'upstream = "github-linguist/linguist"',
        f'revision = "{revision}"',
        f'source = "{url}"',
        f'sha256 = "{digest}"',
        'license = "MIT"',
        "",
    ]

    kept = 0
    for name, entry in sorted(languages.items()):
        role = ROLE.get(entry.get("type"))
        if role is None:
            continue
        extensions = [e.lstrip(".").lower() for e in entry.get("extensions", [])]
        filenames = entry.get("filenames", [])
        interpreters = entry.get("interpreters", [])
        if not (extensions or filenames or interpreters):
            continue
        kept += 1
        lines.append(f"[{slug(name)}]")
        # json.dumps, not repr: TOML basic strings escape the way JSON does,
        # and names like `Cap'n Proto` and `Ren'Py` break anything cruder.
        lines.append("display-name = " + json.dumps(name))
        lines.append(f'role = "{role}"')
        if extensions:
            lines.append("extensions = " + json.dumps(extensions))
        if filenames:
            lines.append("filenames = " + json.dumps(filenames))
        if interpreters:
            lines.append("shebangs = " + json.dumps(interpreters))
        lines.append("")

    with open("data/imported/linguist.toml", "w") as handle:
        handle.write("\n".join(lines))
    print(f"{kept} languages imported from linguist@{revision[:12]} (sha256 {digest[:12]}…)")


if __name__ == "__main__":
    main()
