#!/usr/bin/env python3
"""Absorb linguist's content heuristics for contested extensions.

langbank declines to name a language when several claim an extension and none
claims to win — 127 of them. Linguist settles most of those by *reading* the
file, and publishes the rules for it: an ordered list of regexes per extension,
first match wins.

Langbank does not read files, so it carries the rules rather than the answers,
exactly as it carries version probes rather than versions. A consumer that has
the bytes can run them; one that does not is no worse off than before.

Six rule shapes in the upstream collapse into one here: every rule is a language
plus a list of clauses, all of which must match, where a clause is patterns any
of which may match and negative patterns none of which may. A rule with no
clauses always matches, which is how linguist spells a fallback.

    tools/sync-heuristics.py check
    tools/sync-heuristics.py create
"""
import argparse
import glob
import json
import re
import sys
import urllib.request

import yaml

UPSTREAM = "https://raw.githubusercontent.com/github-linguist/linguist/main/lib/linguist/heuristics.yml"
OUT = "data/heuristics.toml"

# Rust's regex crate rejects lookaround; a consumer using it cannot compile
# these three rules and should know that rather than discover it at run time.
UNPORTABLE = re.compile(r"\(\?<?[=!]|\\[1-9]")


def listify(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def languages():
    out = {}
    for path in sorted(glob.glob("data/languages/*.toml")):
        text = open(path).read()
        lid = re.search(r'^id = "([^"]+)"', text, re.M).group(1)
        display = re.search(r'^display-name = "([^"]+)"', text, re.M)
        out[(display.group(1) if display else lid)] = lid
    return out


def clauses(rule, named):
    """Every condition that must hold, flattened out of linguist's six shapes."""
    out = []

    def one(node):
        patterns = listify(node.get("pattern"))
        if "named_pattern" in node:
            patterns += listify(named.get(node["named_pattern"]))
        negatives = listify(node.get("negative_pattern"))
        if patterns or negatives:
            out.append({"patterns": patterns, "negative": negatives})

    one(rule)
    for sub in rule.get("and", []):
        one(sub)
    return out


def build(document, known):
    named = document.get("named_patterns", {})
    blocks, dropped = [], []
    for block in document["disambiguations"]:
        rules = []
        for rule in block.get("rules", []):
            names = listify(rule.get("language"))
            mapped = [known[n] for n in names if n in known]
            if len(mapped) != len(names) or not mapped:
                # Dropping a rule would shift the ones after it, and these are
                # evaluated in order, so the whole block goes.
                dropped.append((block.get("extensions", []), names))
                rules = None
                break
            conditions = clauses(rule, named)
            portable = not any(
                UNPORTABLE.search(pattern)
                for condition in conditions
                for pattern in condition["patterns"] + condition["negative"]
            )
            rules.append({"language": mapped[0], "clauses": conditions, "portable": portable})
        if rules:
            blocks.append({
                "extensions": [e.lstrip(".").lower() for e in block.get("extensions", [])],
                "rules": rules,
            })
    return blocks, dropped


def render(blocks):
    lines = [
        "# @generated by tools/sync-heuristics.py from github-linguist/linguist (MIT).",
        "#",
        "# Ordered rules that name a language by reading a file, for extensions",
        "# several languages claim. Langbank does not read files; it carries the",
        "# rules so a consumer that has the bytes can settle what langbank cannot.",
        "# First rule whose clauses all match wins. A rule with no clauses always",
        "# matches, which is how a fallback is spelled.",
        "",
    ]
    for block in blocks:
        lines.append("[[disambiguation]]")
        lines.append(f"extensions = {json.dumps(block['extensions'], ensure_ascii=False)}")
        for rule in block["rules"]:
            lines.append("")
            lines.append("  [[disambiguation.rule]]")
            lines.append(f"  language = {json.dumps(rule['language'], ensure_ascii=False)}")
            if not rule["portable"]:
                lines.append("  portable = false")
            for clause in rule["clauses"]:
                lines.append("")
                lines.append("    [[disambiguation.rule.clause]]")
                lines.append(f"    patterns = {json.dumps(clause['patterns'], ensure_ascii=False)}")
                if clause["negative"]:
                    lines.append(f"    negative = {json.dumps(clause['negative'], ensure_ascii=False)}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["check", "create"])
    args = parser.parse_args()

    document = yaml.safe_load(urllib.request.urlopen(UPSTREAM, timeout=90).read())
    blocks, dropped = build(document, languages())
    rules = sum(len(b["rules"]) for b in blocks)
    unportable = sum(1 for b in blocks for r in b["rules"] if not r["portable"])

    if args.command == "check":
        carried = open(OUT).read() if glob.glob(OUT) else ""
        current = carried.count("[[disambiguation]]")
        print(f"linguist publishes {len(document['disambiguations'])} disambiguation blocks; "
              f"{len(blocks)} map onto langbank languages, {len(dropped)} do not")
        print(f"  langbank carries {current}")
        print(f"  rules: {rules}, of which {unportable} use constructs Rust's regex rejects")
        return 1 if current != len(blocks) else 0

    open(OUT, "w").write(render(blocks))
    print(f"wrote {len(blocks)} disambiguation blocks, {rules} rules "
          f"({unportable} not portable to Rust regex); {len(dropped)} blocks dropped "
          f"for naming a language langbank does not carry")
    return 0


if __name__ == "__main__":
    sys.exit(main())
