// @generated by tools/verbosity. Do not edit by hand.
//! Relative source verbosity of the profiled languages.
//!
//! Every number here is a statistic derived from the Exercism corpus: how much
//! program text each language needs for exercises that two languages both
//! implement, with comments and blank lines removed. That corpus is licensed
//! under the MIT License. Entl does not redistribute it; only these measurements.
//!
//! Entl reports the measurement, not a verdict. Verbosity here is source size on small self-contained pieces, which rewards languages with terse standard libraries and charges languages that require declarations, imports, or a class to hold `main`. It does not extrapolate to large programs: measured on a mid-sized one instead, the same languages spread roughly twice as far apart. It is not a claim
//! about readability.
//!
//! It is also not a porting factor. This measures what a language needs when
//! someone writes a solution from the specification. Translating an existing
//! program into another language is a different quantity and can run the other
//! way: Bun's Zig-to-Rust rewrite expanded by about 1.37x in tokens, while
//! independently written Rust and Zig solutions put Rust at roughly 0.7x Zig.
//!
//! See `docs/verbosity-exercism.md` for the method, the full matrix, and how far a
//! single index per language falls short of explaining the pairs it came from.

/// The corpus the measurements were taken from.
pub const VERBOSITY_CORPUS: &str = "https://github.com/exercism";

/// The corpus revision the checked-in numbers were measured at.
pub const VERBOSITY_CORPUS_REVISION: &str = "bash@8b047b8790e9 c@2fb6107548ef cpp@d2babb2bd750 csharp@196a175a409c go@f6c0bf28b808 java@fc789fb3584b javascript@295540983b63 kotlin@c0b340342de0 php@a322d8c3d971 python@250bf1905054 ruby@4d2d31541992 rust@7a701dc83349 scala@997041534a75 swift@55bc7f22d634 typescript@49f93d57cc5e zig@4d31034eb595";

/// The language every index is expressed relative to.
pub const VERBOSITY_BASELINE: &str = "c";

/// How much source text a language needs, relative to [`VERBOSITY_BASELINE`].
///
/// A value of 2.0 means that on the tasks measured, this language took about
/// twice as much program text as the baseline.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LanguageVerbosity {
    /// Relative bytes of program text, ignoring indentation.
    pub bytes: f32,
    /// Relative count of lines that hold program text.
    pub lines: f32,
    /// Corpus tasks this language contributed.
    pub tasks: u32,
    /// The largest fractional gap between this language's index ratio and a
    /// ratio measured directly against one other language. A single index per
    /// language cannot reproduce every pair exactly; this is how far off it
    /// gets. Prefer [`verbosity_ratio`] when comparing two specific languages.
    pub deviation: f32,
}

/// A ratio measured directly between two languages, on the tasks both
/// implement. More accurate for that pair than dividing two indexes.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VerbosityRatio {
    /// Bytes of program text in the left language per byte in the right.
    pub bytes: f32,
    /// Lines in the left language per line in the right.
    pub lines: f32,
    /// Tasks both languages implement.
    pub tasks: u32,
}

impl VerbosityRatio {
    /// The same measurement with the languages swapped.
    pub fn inverted(&self) -> Self {
        Self {
            bytes: 1.0 / self.bytes,
            lines: 1.0 / self.lines,
            tasks: self.tasks,
        }
    }
}

static VERBOSITY: &[(&str, LanguageVerbosity)] = &[
    (
        "c",
        LanguageVerbosity {
            bytes: 1.0000,
            lines: 1.0000,
            tasks: 85,
            deviation: 0.0661,
        },
    ),
    (
        "c-sharp",
        LanguageVerbosity {
            bytes: 0.6409,
            lines: 0.5795,
            tasks: 144,
            deviation: 0.0314,
        },
    ),
    (
        "cpp",
        LanguageVerbosity {
            bytes: 0.8892,
            lines: 0.8393,
            tasks: 86,
            deviation: 0.0430,
        },
    ),
    (
        "go",
        LanguageVerbosity {
            bytes: 0.5767,
            lines: 0.6851,
            tasks: 148,
            deviation: 0.0405,
        },
    ),
    (
        "java",
        LanguageVerbosity {
            bytes: 0.8213,
            lines: 0.7084,
            tasks: 145,
            deviation: 0.0283,
        },
    ),
    (
        "javascript",
        LanguageVerbosity {
            bytes: 0.5369,
            lines: 0.5270,
            tasks: 139,
            deviation: 0.0583,
        },
    ),
    (
        "kotlin",
        LanguageVerbosity {
            bytes: 0.5086,
            lines: 0.3620,
            tasks: 95,
            deviation: 0.0414,
        },
    ),
    (
        "php",
        LanguageVerbosity {
            bytes: 0.6077,
            lines: 0.6470,
            tasks: 117,
            deviation: 0.0310,
        },
    ),
    (
        "python",
        LanguageVerbosity {
            bytes: 0.4069,
            lines: 0.3185,
            tasks: 140,
            deviation: 0.0259,
        },
    ),
    (
        "ruby",
        LanguageVerbosity {
            bytes: 0.4286,
            lines: 0.5279,
            tasks: 115,
            deviation: 0.0521,
        },
    ),
    (
        "rust",
        LanguageVerbosity {
            bytes: 0.5937,
            lines: 0.6070,
            tasks: 106,
            deviation: 0.0600,
        },
    ),
    (
        "scala",
        LanguageVerbosity {
            bytes: 0.5383,
            lines: 0.3954,
            tasks: 101,
            deviation: 0.0583,
        },
    ),
    (
        "shell",
        LanguageVerbosity {
            bytes: 0.4484,
            lines: 0.5232,
            tasks: 98,
            deviation: 0.0661,
        },
    ),
    (
        "swift",
        LanguageVerbosity {
            bytes: 0.5842,
            lines: 0.5654,
            tasks: 106,
            deviation: 0.0513,
        },
    ),
    (
        "typescript",
        LanguageVerbosity {
            bytes: 0.6375,
            lines: 0.6111,
            tasks: 111,
            deviation: 0.0600,
        },
    ),
    (
        "zig",
        LanguageVerbosity {
            bytes: 0.6632,
            lines: 0.6357,
            tasks: 98,
            deviation: 0.0544,
        },
    ),
];

static RATIOS: &[(&str, &str, VerbosityRatio)] = &[
    (
        "c",
        "c-sharp",
        VerbosityRatio {
            bytes: 1.5765,
            lines: 1.7310,
            tasks: 85,
        },
    ),
    (
        "c",
        "cpp",
        VerbosityRatio {
            bytes: 1.0862,
            lines: 1.1690,
            tasks: 75,
        },
    ),
    (
        "c",
        "go",
        VerbosityRatio {
            bytes: 1.8015,
            lines: 1.5247,
            tasks: 85,
        },
    ),
    (
        "c",
        "java",
        VerbosityRatio {
            bytes: 1.2049,
            lines: 1.3973,
            tasks: 85,
        },
    ),
    (
        "c",
        "javascript",
        VerbosityRatio {
            bytes: 1.8968,
            lines: 1.9251,
            tasks: 84,
        },
    ),
    (
        "c",
        "kotlin",
        VerbosityRatio {
            bytes: 1.9340,
            lines: 2.7629,
            tasks: 76,
        },
    ),
    (
        "c",
        "php",
        VerbosityRatio {
            bytes: 1.6706,
            lines: 1.5623,
            tasks: 81,
        },
    ),
    (
        "c",
        "python",
        VerbosityRatio {
            bytes: 2.4542,
            lines: 3.1375,
            tasks: 83,
        },
    ),
    (
        "c",
        "ruby",
        VerbosityRatio {
            bytes: 2.2986,
            lines: 1.8222,
            tasks: 79,
        },
    ),
    (
        "c",
        "rust",
        VerbosityRatio {
            bytes: 1.7420,
            lines: 1.7159,
            tasks: 71,
        },
    ),
    (
        "c",
        "scala",
        VerbosityRatio {
            bytes: 1.9035,
            lines: 2.5557,
            tasks: 73,
        },
    ),
    (
        "c",
        "shell",
        VerbosityRatio {
            bytes: 2.0828,
            lines: 1.8030,
            tasks: 74,
        },
    ),
    (
        "c",
        "swift",
        VerbosityRatio {
            bytes: 1.7385,
            lines: 1.7996,
            tasks: 78,
        },
    ),
    (
        "c",
        "typescript",
        VerbosityRatio {
            bytes: 1.5390,
            lines: 1.6205,
            tasks: 79,
        },
    ),
    (
        "c",
        "zig",
        VerbosityRatio {
            bytes: 1.5148,
            lines: 1.5605,
            tasks: 75,
        },
    ),
    (
        "c-sharp",
        "cpp",
        VerbosityRatio {
            bytes: 0.7258,
            lines: 0.7102,
            tasks: 86,
        },
    ),
    (
        "c-sharp",
        "go",
        VerbosityRatio {
            bytes: 1.1094,
            lines: 0.8304,
            tasks: 144,
        },
    ),
    (
        "c-sharp",
        "java",
        VerbosityRatio {
            bytes: 0.7826,
            lines: 0.8072,
            tasks: 141,
        },
    ),
    (
        "c-sharp",
        "javascript",
        VerbosityRatio {
            bytes: 1.1887,
            lines: 1.0746,
            tasks: 135,
        },
    ),
    (
        "c-sharp",
        "kotlin",
        VerbosityRatio {
            bytes: 1.2743,
            lines: 1.6165,
            tasks: 95,
        },
    ),
    (
        "c-sharp",
        "php",
        VerbosityRatio {
            bytes: 1.0625,
            lines: 0.9124,
            tasks: 114,
        },
    ),
    (
        "c-sharp",
        "python",
        VerbosityRatio {
            bytes: 1.5774,
            lines: 1.7640,
            tasks: 137,
        },
    ),
    (
        "c-sharp",
        "ruby",
        VerbosityRatio {
            bytes: 1.5197,
            lines: 1.1268,
            tasks: 112,
        },
    ),
    (
        "c-sharp",
        "rust",
        VerbosityRatio {
            bytes: 1.0613,
            lines: 0.9481,
            tasks: 97,
        },
    ),
    (
        "c-sharp",
        "scala",
        VerbosityRatio {
            bytes: 1.1794,
            lines: 1.5106,
            tasks: 100,
        },
    ),
    (
        "c-sharp",
        "shell",
        VerbosityRatio {
            bytes: 1.4445,
            lines: 1.1106,
            tasks: 98,
        },
    ),
    (
        "c-sharp",
        "swift",
        VerbosityRatio {
            bytes: 1.0698,
            lines: 1.0117,
            tasks: 106,
        },
    ),
    (
        "c-sharp",
        "typescript",
        VerbosityRatio {
            bytes: 0.9874,
            lines: 0.9417,
            tasks: 111,
        },
    ),
    (
        "c-sharp",
        "zig",
        VerbosityRatio {
            bytes: 0.9967,
            lines: 0.9445,
            tasks: 96,
        },
    ),
    (
        "cpp",
        "go",
        VerbosityRatio {
            bytes: 1.5442,
            lines: 1.2243,
            tasks: 86,
        },
    ),
    (
        "cpp",
        "java",
        VerbosityRatio {
            bytes: 1.0784,
            lines: 1.1801,
            tasks: 86,
        },
    ),
    (
        "cpp",
        "javascript",
        VerbosityRatio {
            bytes: 1.6851,
            lines: 1.6212,
            tasks: 86,
        },
    ),
    (
        "cpp",
        "kotlin",
        VerbosityRatio {
            bytes: 1.7795,
            lines: 2.3359,
            tasks: 77,
        },
    ),
    (
        "cpp",
        "php",
        VerbosityRatio {
            bytes: 1.4612,
            lines: 1.3034,
            tasks: 82,
        },
    ),
    (
        "cpp",
        "python",
        VerbosityRatio {
            bytes: 2.1637,
            lines: 2.6543,
            tasks: 84,
        },
    ),
    (
        "cpp",
        "ruby",
        VerbosityRatio {
            bytes: 1.9884,
            lines: 1.5118,
            tasks: 85,
        },
    ),
    (
        "cpp",
        "rust",
        VerbosityRatio {
            bytes: 1.4717,
            lines: 1.3836,
            tasks: 72,
        },
    ),
    (
        "cpp",
        "scala",
        VerbosityRatio {
            bytes: 1.6607,
            lines: 2.1465,
            tasks: 76,
        },
    ),
    (
        "cpp",
        "shell",
        VerbosityRatio {
            bytes: 1.9212,
            lines: 1.5957,
            tasks: 70,
        },
    ),
    (
        "cpp",
        "swift",
        VerbosityRatio {
            bytes: 1.5059,
            lines: 1.4818,
            tasks: 80,
        },
    ),
    (
        "cpp",
        "typescript",
        VerbosityRatio {
            bytes: 1.4094,
            lines: 1.3722,
            tasks: 76,
        },
    ),
    (
        "cpp",
        "zig",
        VerbosityRatio {
            bytes: 1.3983,
            lines: 1.3635,
            tasks: 71,
        },
    ),
    (
        "go",
        "java",
        VerbosityRatio {
            bytes: 0.7116,
            lines: 0.9712,
            tasks: 143,
        },
    ),
    (
        "go",
        "javascript",
        VerbosityRatio {
            bytes: 1.0768,
            lines: 1.2916,
            tasks: 136,
        },
    ),
    (
        "go",
        "kotlin",
        VerbosityRatio {
            bytes: 1.1732,
            lines: 1.9665,
            tasks: 95,
        },
    ),
    (
        "go",
        "php",
        VerbosityRatio {
            bytes: 0.9567,
            lines: 1.0575,
            tasks: 115,
        },
    ),
    (
        "go",
        "python",
        VerbosityRatio {
            bytes: 1.4172,
            lines: 2.1168,
            tasks: 138,
        },
    ),
    (
        "go",
        "ruby",
        VerbosityRatio {
            bytes: 1.3815,
            lines: 1.3622,
            tasks: 112,
        },
    ),
    (
        "go",
        "rust",
        VerbosityRatio {
            bytes: 0.9823,
            lines: 1.1387,
            tasks: 98,
        },
    ),
    (
        "go",
        "scala",
        VerbosityRatio {
            bytes: 1.0592,
            lines: 1.7539,
            tasks: 100,
        },
    ),
    (
        "go",
        "shell",
        VerbosityRatio {
            bytes: 1.2341,
            lines: 1.2328,
            tasks: 98,
        },
    ),
    (
        "go",
        "swift",
        VerbosityRatio {
            bytes: 0.9646,
            lines: 1.1964,
            tasks: 106,
        },
    ),
    (
        "go",
        "typescript",
        VerbosityRatio {
            bytes: 0.8910,
            lines: 1.1050,
            tasks: 111,
        },
    ),
    (
        "go",
        "zig",
        VerbosityRatio {
            bytes: 0.8880,
            lines: 1.0914,
            tasks: 98,
        },
    ),
    (
        "java",
        "javascript",
        VerbosityRatio {
            bytes: 1.5291,
            lines: 1.3430,
            tasks: 134,
        },
    ),
    (
        "java",
        "kotlin",
        VerbosityRatio {
            bytes: 1.6344,
            lines: 1.9404,
            tasks: 94,
        },
    ),
    (
        "java",
        "php",
        VerbosityRatio {
            bytes: 1.3518,
            lines: 1.0991,
            tasks: 113,
        },
    ),
    (
        "java",
        "python",
        VerbosityRatio {
            bytes: 2.0066,
            lines: 2.1886,
            tasks: 135,
        },
    ),
    (
        "java",
        "ruby",
        VerbosityRatio {
            bytes: 1.9148,
            lines: 1.3524,
            tasks: 111,
        },
    ),
    (
        "java",
        "rust",
        VerbosityRatio {
            bytes: 1.3668,
            lines: 1.1383,
            tasks: 96,
        },
    ),
    (
        "java",
        "scala",
        VerbosityRatio {
            bytes: 1.5337,
            lines: 1.8093,
            tasks: 100,
        },
    ),
    (
        "java",
        "shell",
        VerbosityRatio {
            bytes: 1.8833,
            lines: 1.3794,
            tasks: 97,
        },
    ),
    (
        "java",
        "swift",
        VerbosityRatio {
            bytes: 1.3683,
            lines: 1.2249,
            tasks: 105,
        },
    ),
    (
        "java",
        "typescript",
        VerbosityRatio {
            bytes: 1.2804,
            lines: 1.1513,
            tasks: 110,
        },
    ),
    (
        "java",
        "zig",
        VerbosityRatio {
            bytes: 1.2684,
            lines: 1.1391,
            tasks: 97,
        },
    ),
    (
        "javascript",
        "kotlin",
        VerbosityRatio {
            bytes: 1.0715,
            lines: 1.4475,
            tasks: 95,
        },
    ),
    (
        "javascript",
        "php",
        VerbosityRatio {
            bytes: 0.8871,
            lines: 0.8206,
            tasks: 112,
        },
    ),
    (
        "javascript",
        "python",
        VerbosityRatio {
            bytes: 1.3387,
            lines: 1.6933,
            tasks: 132,
        },
    ),
    (
        "javascript",
        "ruby",
        VerbosityRatio {
            bytes: 1.2583,
            lines: 1.0220,
            tasks: 113,
        },
    ),
    (
        "javascript",
        "rust",
        VerbosityRatio {
            bytes: 0.9000,
            lines: 0.8482,
            tasks: 95,
        },
    ),
    (
        "javascript",
        "scala",
        VerbosityRatio {
            bytes: 0.9393,
            lines: 1.2705,
            tasks: 100,
        },
    ),
    (
        "javascript",
        "shell",
        VerbosityRatio {
            bytes: 1.2599,
            lines: 1.0316,
            tasks: 96,
        },
    ),
    (
        "javascript",
        "swift",
        VerbosityRatio {
            bytes: 0.9095,
            lines: 0.9221,
            tasks: 105,
        },
    ),
    (
        "javascript",
        "typescript",
        VerbosityRatio {
            bytes: 0.8539,
            lines: 0.8680,
            tasks: 111,
        },
    ),
    (
        "javascript",
        "zig",
        VerbosityRatio {
            bytes: 0.8060,
            lines: 0.8105,
            tasks: 96,
        },
    ),
    (
        "kotlin",
        "php",
        VerbosityRatio {
            bytes: 0.8355,
            lines: 0.5635,
            tasks: 88,
        },
    ),
    (
        "kotlin",
        "python",
        VerbosityRatio {
            bytes: 1.2570,
            lines: 1.1634,
            tasks: 94,
        },
    ),
    (
        "kotlin",
        "ruby",
        VerbosityRatio {
            bytes: 1.1983,
            lines: 0.6803,
            tasks: 91,
        },
    ),
    (
        "kotlin",
        "rust",
        VerbosityRatio {
            bytes: 0.8922,
            lines: 0.6209,
            tasks: 79,
        },
    ),
    (
        "kotlin",
        "scala",
        VerbosityRatio {
            bytes: 0.9822,
            lines: 0.9428,
            tasks: 82,
        },
    ),
    (
        "kotlin",
        "shell",
        VerbosityRatio {
            bytes: 1.1488,
            lines: 0.6857,
            tasks: 75,
        },
    ),
    (
        "kotlin",
        "swift",
        VerbosityRatio {
            bytes: 0.8544,
            lines: 0.6235,
            tasks: 88,
        },
    ),
    (
        "kotlin",
        "typescript",
        VerbosityRatio {
            bytes: 0.7837,
            lines: 0.5824,
            tasks: 86,
        },
    ),
    (
        "kotlin",
        "zig",
        VerbosityRatio {
            bytes: 0.7834,
            lines: 0.5747,
            tasks: 75,
        },
    ),
    (
        "php",
        "python",
        VerbosityRatio {
            bytes: 1.5214,
            lines: 2.0544,
            tasks: 111,
        },
    ),
    (
        "php",
        "ruby",
        VerbosityRatio {
            bytes: 1.4236,
            lines: 1.2359,
            tasks: 102,
        },
    ),
    (
        "php",
        "rust",
        VerbosityRatio {
            bytes: 1.0177,
            lines: 1.0811,
            tasks: 84,
        },
    ),
    (
        "php",
        "scala",
        VerbosityRatio {
            bytes: 1.1254,
            lines: 1.6252,
            tasks: 89,
        },
    ),
    (
        "php",
        "shell",
        VerbosityRatio {
            bytes: 1.3597,
            lines: 1.2461,
            tasks: 90,
        },
    ),
    (
        "php",
        "swift",
        VerbosityRatio {
            bytes: 1.0375,
            lines: 1.1327,
            tasks: 98,
        },
    ),
    (
        "php",
        "typescript",
        VerbosityRatio {
            bytes: 0.9827,
            lines: 1.0882,
            tasks: 100,
        },
    ),
    (
        "php",
        "zig",
        VerbosityRatio {
            bytes: 0.8999,
            lines: 1.0185,
            tasks: 92,
        },
    ),
    (
        "python",
        "ruby",
        VerbosityRatio {
            bytes: 0.9562,
            lines: 0.6001,
            tasks: 111,
        },
    ),
    (
        "python",
        "rust",
        VerbosityRatio {
            bytes: 0.6838,
            lines: 0.5113,
            tasks: 96,
        },
    ),
    (
        "python",
        "scala",
        VerbosityRatio {
            bytes: 0.7756,
            lines: 0.8104,
            tasks: 98,
        },
    ),
    (
        "python",
        "shell",
        VerbosityRatio {
            bytes: 0.8930,
            lines: 0.6018,
            tasks: 96,
        },
    ),
    (
        "python",
        "swift",
        VerbosityRatio {
            bytes: 0.6952,
            lines: 0.5570,
            tasks: 105,
        },
    ),
    (
        "python",
        "typescript",
        VerbosityRatio {
            bytes: 0.6477,
            lines: 0.5347,
            tasks: 108,
        },
    ),
    (
        "python",
        "zig",
        VerbosityRatio {
            bytes: 0.6144,
            lines: 0.5017,
            tasks: 93,
        },
    ),
    (
        "ruby",
        "rust",
        VerbosityRatio {
            bytes: 0.6951,
            lines: 0.8602,
            tasks: 89,
        },
    ),
    (
        "ruby",
        "scala",
        VerbosityRatio {
            bytes: 0.7898,
            lines: 1.3474,
            tasks: 95,
        },
    ),
    (
        "ruby",
        "shell",
        VerbosityRatio {
            bytes: 1.0056,
            lines: 1.0426,
            tasks: 84,
        },
    ),
    (
        "ruby",
        "swift",
        VerbosityRatio {
            bytes: 0.7257,
            lines: 0.9331,
            tasks: 101,
        },
    ),
    (
        "ruby",
        "typescript",
        VerbosityRatio {
            bytes: 0.6832,
            lines: 0.8714,
            tasks: 96,
        },
    ),
    (
        "ruby",
        "zig",
        VerbosityRatio {
            bytes: 0.6611,
            lines: 0.8369,
            tasks: 86,
        },
    ),
    (
        "rust",
        "scala",
        VerbosityRatio {
            bytes: 1.0850,
            lines: 1.5160,
            tasks: 81,
        },
    ),
    (
        "rust",
        "shell",
        VerbosityRatio {
            bytes: 1.3383,
            lines: 1.1887,
            tasks: 78,
        },
    ),
    (
        "rust",
        "swift",
        VerbosityRatio {
            bytes: 1.0684,
            lines: 1.1263,
            tasks: 84,
        },
    ),
    (
        "rust",
        "typescript",
        VerbosityRatio {
            bytes: 0.8753,
            lines: 0.9437,
            tasks: 84,
        },
    ),
    (
        "rust",
        "zig",
        VerbosityRatio {
            bytes: 0.8892,
            lines: 0.9405,
            tasks: 73,
        },
    ),
    (
        "scala",
        "shell",
        VerbosityRatio {
            bytes: 1.2068,
            lines: 0.7875,
            tasks: 71,
        },
    ),
    (
        "scala",
        "swift",
        VerbosityRatio {
            bytes: 0.9405,
            lines: 0.7179,
            tasks: 89,
        },
    ),
    (
        "scala",
        "typescript",
        VerbosityRatio {
            bytes: 0.8309,
            lines: 0.6477,
            tasks: 84,
        },
    ),
    (
        "scala",
        "zig",
        VerbosityRatio {
            bytes: 0.7814,
            lines: 0.6144,
            tasks: 77,
        },
    ),
    (
        "shell",
        "swift",
        VerbosityRatio {
            bytes: 0.7819,
            lines: 0.9238,
            tasks: 83,
        },
    ),
    (
        "shell",
        "typescript",
        VerbosityRatio {
            bytes: 0.7139,
            lines: 0.8594,
            tasks: 88,
        },
    ),
    (
        "shell",
        "zig",
        VerbosityRatio {
            bytes: 0.6734,
            lines: 0.8221,
            tasks: 81,
        },
    ),
    (
        "swift",
        "typescript",
        VerbosityRatio {
            bytes: 0.9096,
            lines: 0.9106,
            tasks: 94,
        },
    ),
    (
        "swift",
        "zig",
        VerbosityRatio {
            bytes: 0.8414,
            lines: 0.8697,
            tasks: 82,
        },
    ),
    (
        "typescript",
        "zig",
        VerbosityRatio {
            bytes: 0.9090,
            lines: 0.9194,
            tasks: 86,
        },
    ),
];

/// The verbosity of a language by profile ID, if the corpus covers it.
pub fn verbosity(language: &str) -> Option<&'static LanguageVerbosity> {
    VERBOSITY
        .binary_search_by_key(&language, |(id, _)| *id)
        .ok()
        .map(|index| &VERBOSITY[index].1)
}

/// The measured ratio of `left` to `right`, if the corpus covers both with
/// enough tasks in common.
pub fn verbosity_ratio(left: &str, right: &str) -> Option<VerbosityRatio> {
    if left == right {
        return None;
    }
    let (key, inverted) = if left < right {
        ((left, right), false)
    } else {
        ((right, left), true)
    };
    let found = RATIOS
        .binary_search_by_key(&key, |(left, right, _)| (*left, *right))
        .ok()
        .map(|index| RATIOS[index].2)?;
    Some(if inverted { found.inverted() } else { found })
}

/// Every measured pair, ordered and deduplicated: each pair appears once, with
/// the alphabetically first language on the left.
pub fn verbosity_ratios() -> impl Iterator<Item = (&'static str, &'static str, VerbosityRatio)> {
    RATIOS
        .iter()
        .map(|(left, right, ratio)| (*left, *right, *ratio))
}
